"""UI state models for graph modes, shell review posture, authority presentation, and device onboarding boundaries."""

from .models import (
    AuthoritySurface,
    ActionAuditEntry,
    BindingReviewSummary,
    FirstSignalSummary,
    FirstSignalTracePoint,
    SessionEventSummary,
    TrustedSessionSummary,
    DeviceLifecycleSummary,
    PersistedSessionSurface,
    GraphModeSession,
    ReconciliationSummary,
    VariableHealthSummary,
    WorkbenchReviewState,
)
from .session_state import UISessionFactory, UISessionState
from .demo_shell import (
    PersistentInfoBar,
    DockLayoutPreference,
    TracePresentationStyle,
    LegendPresentationPreferences,
    GraphAutosavePreferences,
    SignalLensDescriptor,
    UserDemoScenario,
    UserDemoModeSummary,
    OperatorShellFoundation,
)
from .demo_builders import (
    build_persistent_info_bar,
    build_user_demo_mode_summary,
    build_operator_shell_foundation,
    dump_operator_shell_foundation_dict,
)
from .visible_shell import (
    MENU_FILE,
    MENU_HELP,
    MENU_MODE,
    MENU_SETTINGS,
    MENU_TESTING,
    MENU_VIEW,
    MENU_WORKSPACE,
    MenuActionSpec,
    MenuSpec,
    VisibleOperatorShellSpec,
    WorkspaceSpec,
    build_visible_operator_shell_spec,
)
from .shell_views import (
    ControlTabId,
    ExplorerTabId,
    DeviceIoRow,
    DeviceIoSummary,
    EventConsoleRow,
    MappingApplyReviewPanel,
    MappingApplyWorkflowState,
    MappingAuthorityState,
    MappingDirection,
    MappingRow,
    MappingStatus,
    MappingSummary,
    SavedShellView,
    ShellLayoutSnapshot,
    ShellPanelVisibility,
    ShellViewCatalog,
    build_mapping_apply_review_panel,
    build_device_io_rows,
    build_mapping_rows,
    classify_mapping_authority_state,
    default_shell_views,
    derive_event_console_rows,
    summarize_device_io_rows,
    summarize_mapping_rows,
)
from .qt_shell import (
    build_visible_shell_spec_for_demo,
    default_demo_shell_viewmodel,
    detect_gui_dependencies,
)
from .live_runtime import (
    GuardedWriteDecision,
    LiveRuntimeDeviceRecord,
    LiveRuntimeEngine,
    LiveRuntimeSnapshot,
    LiveSignalDescriptor,
    LiveSignalSnapshot,
    WriteTargetDescriptor,
)
from .viewmodels import (
    BindingReviewCardViewModel,
    DeviceCardViewModel,
    FirstSignalCardViewModel,
    GraphPanelViewModel,
    LifecycleSummaryCardViewModel,
    ReconciliationCardViewModel,
    ShellViewModel,
    ShellViewModelBuilder,
    VariableHealthCardViewModel,
    WorkbenchCardViewModel,
)

MODULE_DECLARATION = {
    "module_id": "UDQ-CODE-PKG-UI",
    "implements_requirements": [
        "UDQ-REQ-UI-001",
        "UDQ-REQ-UI-003",
        "UDQ-REQ-UI-004",
        "UDQ-REQ-UI-006",
        "UDQ-REQ-UI-007",
    ],
    "governed_by": [
        "UDQ-UI-MOD-001",
        "UDQ-UI-SPEC-004",
        "UDQ-IMP-MAP-001",
        "UDQ-IMP-GUIDE-001",
    ],
    "subsystem": "UI",
    "invariant_hooks": [
        "UDQ-INV-STATE-003",
        "UDQ-INV-STATE-004",
        "UDQ-INV-TRANS-004",
    ],
    "proof_scope": "graph-mode, authority-surface, shell-session, lifecycle review summaries, device onboarding posture, and shell-facing view-model state without widget implementation",
}

__all__ = [
    "PersistentInfoBar",
    "DockLayoutPreference",
    "TracePresentationStyle",
    "LegendPresentationPreferences",
    "GraphAutosavePreferences",
    "SignalLensDescriptor",
    "UserDemoScenario",
    "UserDemoModeSummary",
    "OperatorShellFoundation",
    "build_persistent_info_bar",
    "build_user_demo_mode_summary",
    "build_operator_shell_foundation",
    "dump_operator_shell_foundation_dict",
    "MENU_FILE",
    "MENU_VIEW",
    "MENU_WORKSPACE",
    "MENU_MODE",
    "MENU_SETTINGS",
    "MENU_TESTING",
    "MENU_HELP",
    "MenuActionSpec",
    "MenuSpec",
    "WorkspaceSpec",
    "VisibleOperatorShellSpec",
    "build_visible_operator_shell_spec",
    "ControlTabId",
    "ExplorerTabId",
    "DeviceIoRow",
    "DeviceIoSummary",
    "EventConsoleRow",
    "MappingApplyReviewPanel",
    "MappingApplyWorkflowState",
    "MappingAuthorityState",
    "MappingDirection",
    "MappingRow",
    "MappingStatus",
    "MappingSummary",
    "SavedShellView",
    "ShellLayoutSnapshot",
    "ShellPanelVisibility",
    "ShellViewCatalog",
    "build_mapping_apply_review_panel",
    "build_device_io_rows",
    "build_mapping_rows",
    "classify_mapping_authority_state",
    "default_shell_views",
    "derive_event_console_rows",
    "summarize_device_io_rows",
    "summarize_mapping_rows",
    "build_visible_shell_spec_for_demo",
    "default_demo_shell_viewmodel",
    "detect_gui_dependencies",
    "LiveRuntimeDeviceRecord",
    "LiveRuntimeEngine",
    "LiveRuntimeSnapshot",
    "LiveSignalDescriptor",
    "LiveSignalSnapshot",
    "WriteTargetDescriptor",
    "GuardedWriteDecision",
    "AuthoritySurface",
    "ActionAuditEntry",
    "BindingReviewCardViewModel",
    "BindingReviewSummary",
    "FirstSignalCardViewModel",
    "FirstSignalSummary",
    "FirstSignalTracePoint",
    "SessionEventSummary",
    "TrustedSessionSummary",
    "DeviceCardViewModel",
    "DeviceLifecycleSummary",
    "PersistedSessionSurface",
    "GraphModeSession",
    "GraphPanelViewModel",
    "LifecycleSummaryCardViewModel",
    "MODULE_DECLARATION",
    "ReconciliationCardViewModel",
    "ReconciliationSummary",
    "ShellViewModel",
    "ShellViewModelBuilder",
    "UISessionFactory",
    "UISessionState",
    "VariableHealthCardViewModel",
    "VariableHealthSummary",
    "WorkbenchCardViewModel",
    "WorkbenchReviewState",
]
